// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQnNrzCkGS9kBxWa8FJQGutCNuXKUFm_s',
    appId: '1:1092636434259:web:0db1d280941e756cba0ba6',
    messagingSenderId: '1092636434259',
    projectId: 'firebase-practice-a321123',
    authDomain: 'fir-practice-a321123.firebaseapp.com',
    storageBucket: 'firebase-practice-a321123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlvg2QyHrlfrw2vWqDSCsGxdg_0ZtE8w',
    appId: '1:1092636434259:android:5e1f5eab5d1e5455ba0ba6',
    messagingSenderId: '1092636434259',
    projectId: 'firebase-practice-a321123',
    storageBucket: 'firebase-practice-a321123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD74evaGIDV8Ot-30TbPPmJR5Pa7aSNfdA',
    appId: '1:1092636434259:ios:a0ac2b64d680e588ba0ba6',
    messagingSenderId: '1092636434259',
    projectId: 'firebase-practice-a321123',
    storageBucket: 'firebase-practice-a321123.appspot.com',
    iosClientId: '1092636434259-h853longn24o154plt232r80dikdvg01.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD74evaGIDV8Ot-30TbPPmJR5Pa7aSNfdA',
    appId: '1:1092636434259:ios:cfa3a5a595c81f03ba0ba6',
    messagingSenderId: '1092636434259',
    projectId: 'firebase-practice-a321123',
    storageBucket: 'firebase-practice-a321123.appspot.com',
    iosClientId: '1092636434259-land663ibklsgrj5sk4jsvnuadt7favt.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasePractice.RunnerTests',
  );
}
